<?php
    if (isset($_POST['cloud'])) {
        # code...
    } elseif (isset($_POST['application'])) {
        # code...
    } elseif (isset($_POST['login'])) {
        # code...
    } else {
        # code...
    }

?>